#!/usr/bin/env ruby
require 'drb'
require_relative './lib/storage'

storage = Storage.new
storage.load_from_file './examples/init_from_file'

DRb.start_service 'druby://:9000', storage
puts "Server running at #{DRb.uri}"

trap('INT') { DRb.stop_service }
DRb.thread.join
